# Generated by Django 5.0.4 on 2024-04-29 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='unique_address',
            field=models.CharField(default='http://localhost:8000', max_length=150),
        ),
    ]
